In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = sns.load_dataset('iris')

In [7]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [8]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X = df.drop('species',axis=1)
y = df['species']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [12]:
from sklearn.neighbors  import KNeighborsClassifier

In [13]:
model_knn = KNeighborsClassifier(n_neighbors=5)

In [14]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier()

In [15]:
model_knn.score(X_test,y_test)

0.98

In [16]:
from sklearn.svm import SVC

In [17]:
model_svm = SVC(gamma='auto',C=10,kernel='rbf')

In [18]:
model_svm.fit(X_train,y_train)

SVC(C=10, gamma='auto')

In [19]:
model_svm.score(X_test,y_test)

1.0

In [20]:
#now we use grid search cv

In [21]:
from sklearn.model_selection import GridSearchCV

In [22]:
classifier = GridSearchCV((model_svm),{'C':[10,20,30],'kernel':['rbf','linear']},cv=5,return_train_score=False)

In [23]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(C=10, gamma='auto'),
             param_grid={'C': [10, 20, 30], 'kernel': ['rbf', 'linear']})

In [24]:
classifier.cv_results_

{'mean_fit_time': array([0.00182157, 0.00195389, 0.00165009, 0.00166054, 0.00161328,
        0.00161848]),
 'std_fit_time': array([2.71890582e-04, 3.71703768e-04, 8.91287608e-05, 8.61737759e-05,
        4.29361611e-05, 4.60251861e-05]),
 'mean_score_time': array([0.00129704, 0.00139542, 0.0012476 , 0.00125432, 0.00129218,
        0.00120845]),
 'std_score_time': array([8.41172914e-05, 2.27207097e-04, 1.93899837e-05, 4.34610324e-05,
        1.54492988e-04, 2.66071716e-05]),
 'param_C': masked_array(data=[10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 1.        , 0.96666667, 1.        , 0.96666667,
        1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.9       , 0.9       , 0.9       , 0.9       ,
        0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 0.93333333,
        0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.97333333, 0.96666667, 0.96666667, 0.96      ,
        0.96      ]),
 'std_test_score': array([0.01632993, 0.03887301, 0.03651484, 0.0421637 , 0.03887301,
        0.04898979]),
 'rank_test_score': array([1, 2, 3, 4, 5, 5], dtype=int32)}

In [25]:
results = pd.DataFrame(classifier.cv_results_)

In [26]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001822,0.000272,0.001297,0.000084,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.001954,0.000372,0.001395,0.000227,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,2
2,0.001650,0.000089,0.001248,0.000019,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,3
3,0.001661,0.000086,0.001254,0.000043,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,4
4,0.001613,0.000043,0.001292,0.000154,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,5
5,0.001618,0.000046,0.001208,0.000027,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,5

In [27]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       10          rbf         0.980000
1       10       linear         0.973333
2       20          rbf         0.966667
3       20       linear         0.966667
4       30          rbf         0.960000
5       30       linear         0.960000

In [28]:
#random search cv

In [30]:
from sklearn.model_selection import RandomizedSearchCV

In [31]:
classifier_r = RandomizedSearchCV((model_svm),{'C':[10,20,30],'kernel':['rbf','linear']},cv=5,return_train_score=False,n_iter=2)

In [34]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(C=10, gamma='auto'), n_iter=2,
                   param_distributions={'C': [10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [35]:
classifier_r.cv_results_

{'mean_fit_time': array([0.00347209, 0.00268512]),
 'std_fit_time': array([0.00119037, 0.000254  ]),
 'mean_score_time': array([0.0022203 , 0.00207248]),
 'std_score_time': array([7.57864524e-05, 3.44141672e-05]),
 'param_kernel': masked_array(data=['rbf', 'rbf'],
              mask=[False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[30, 20],
              mask=[False, False],
        fill_value=999999),
 'params': [{'kernel': 'rbf', 'C': 30}, {'kernel': 'rbf', 'C': 20}],
 'split0_test_score': array([0.96666667, 0.96666667]),
 'split1_test_score': array([1., 1.]),
 'split2_test_score': array([0.9, 0.9]),
 'split3_test_score': array([0.93333333, 0.96666667]),
 'split4_test_score': array([1., 1.]),
 'mean_test_score': array([0.96      , 0.96666667]),
 'std_test_score': array([0.03887301, 0.03651484]),
 'rank_test_score': array([2, 1], dtype=int32)}

In [36]:
results_r = pd.DataFrame(classifier_r.cv_results_)

In [37]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001822,0.000272,0.001297,0.000084,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.001954,0.000372,0.001395,0.000227,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,2
2,0.001650,0.000089,0.001248,0.000019,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,3
3,0.001661,0.000086,0.001254,0.000043,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,4
4,0.001613,0.000043,0.001292,0.000154,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,5
5,0.001618,0.000046,0.001208,0.000027,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,5

In [38]:
results_r[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       30          rbf         0.960000
1       20          rbf         0.966667